globals: {}
grids:
  mercator:
    base: GLOBAL_MERCATOR
    num_levels: 22
services:
  demo: {}
  tms: { origin: nw, use_grid_names: true }

layers:
  - name: "2013"
    sources: [2013_cache]
    title: Digitale farbige Orthophotos 2013 (DOP20RGB)

  - name: 2015_cir
    sources: [2015_cir_cache]
    title: Digitale Color-Infrarot-Orthophotos 2015 (DOP20CIR)

  - name: 2016_cir
    sources: [2016_cir_cache]
    title: Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR)

  - name: "2020_true"
    sources: [2020_true_cache]
    title: Digitale farbige TrueOrthophotos 2020 (TrueDOP20RGB) - Sommerbefliegung

  - name: alkis_30
    sources: [alkis_30_cache]
    title: ALKIS Berlin (Amtliches Liegenschaftskatasterinformationssystem)

  - name: atkis_dom
    sources: [atkis_dom_cache]
    title: "ATKIS\xAE DOM - Digitales Oberfl\xE4chenmodell"

  - name: atkis_dgm_1
    sources: [atkis_dgm_1_cache]
    title: "ATKIS\xAE DGM - Digitales Gel\xE4ndemodell"

  - name: strassenbefahrung
    sources: [strassenbefahrung_cache]
    title: "Stra\xDFenbefahrung 2014"

  - name: topplus_p5
    sources: [topplus_p5_cache]
    title: TopPlusOpen

  - name: topplus_web
    sources: [topplus_web_cache]
    title: TopPlusOpen web

  - name: webatlas
    sources: [webatlas_cache]
    title: WebAtlas Berlin

  - name: zoom
    sources: [zoom_cache]
    title: Berlin Zoom

  - name: baumbestand_0
    sources: [baumbestand_0_cache]
    title: Baumbestand Berlin - Straßenbäume

  - name: baumbestand_1
    sources: [baumbestand_1_cache]
    title: Baumbestand Berlin - Anlagenbäume

  - name: baumbestand_3
    sources: [baumbestand_3_cache]
    title: Baumbestand Berlin - Anlagenbäume ohne Datenbankeintrag

  - name: baumbestand_4
    sources: [baumbestand_4_cache]
    title: Baumbestand Berlin - Straßenbäume ohne Datenbankeintrag

  - name: baumbestand_0_1_3_4_merged
    sources: [baumbestand_0_1_3_4_merged_cache]
    title: Baumbestand Berlin - Straßenbäume und Anlagenbäume mit und ohne Datenbankeintrag

  - name: k_oeffbeleucht
    sources: [k_oeffbeleucht_cache]
    title: Öffentliche Beleuchtung

caches:
  1928_cache:
    grids: [mercator]
    sources: [1928_source]

  1953_cache:
    grids: [mercator]
    sources: [1953_source]

  2013_cache:
    grids: [mercator]
    sources: [2013_source]

  2015_cir_cache:
    grids: [mercator]
    sources: [2015_cir_source]

  2016_cir_cache:
    grids: [mercator]
    sources: [2016_cir_source]

  2018_cache:
    grids: [mercator]
    sources: [2018_source]

  2019_cache:
    grids: [mercator]
    sources: [2019_source]

  2020_true_cache:
    grids: [mercator]
    sources: [2020_true_source]

  2020_cache:
    grids: [mercator]
    sources: [2020_source]

  2021_cache:
    grids: [mercator]
    sources: [2021_source]

  alkis_30_cache:
    grids: [mercator]
    sources: [alkis_30_source]

  atkis_dgm_1_cache:
    grids: [mercator]
    sources: [atkis_dgm_1_source]

  atkis_dom_cache:
    grids: [mercator]
    sources: [atkis_dom_source]

  strassenbefahrung_cache:
    grids: [mercator]
    sources: [strassenbefahrung_source]

  topplus_p5_cache:
    grids: [mercator]
    sources: [topplus_p5_source]

  topplus_web_cache:
    grids: [mercator]
    sources: [topplus_web_source]

  webatlas_cache:
    grids: [mercator]
    sources: [webatlas_source]

  zoom_cache:
    grids: [mercator]
    sources: [zoom_source]

  baumbestand_0_cache:
    grids: [mercator]
    sources: [baumbestand_0_source]

  baumbestand_1_cache:
    grids: [mercator]
    sources: [baumbestand_1_source]

  baumbestand_3_cache:
    grids: [mercator]
    sources: [baumbestand_3_source]

  baumbestand_4_cache:
    grids: [mercator]
    sources: [baumbestand_4_source]

  baumbestand_0_1_3_4_merged_cache:
    grids: [mercator]
    sources: [baumbestand_0_1_3_4_merged_source]

  k_oeffbeleucht:
    grids: [mercator]
    sources: [k_oeffbeleucht]

sources:
  2013_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2013"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  2015_cir_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2015_cir"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  2016_cir_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2016_cir"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  2020_true_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_luftbild2020_true_rgb"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  alkis_30_source:
    req:
      format: png
      layers: 30,5,21,0,29,4,7,13,9,25,8,18,20,16,28,12,24,22,34,26,47,46,44,43
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/wmsk_alkis"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  atkis_dgm_1_source:
    req:
      format: png
      layers: 1
      style: default
      transparent: true
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dgm1"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  atkis_dom_source:
    req:
      format: png
      layers: 1
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_dom"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  strassenbefahrung_source:
    req:
      format: png
      layers: 68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_StraDa"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  topplus_p5_source:
    req:
      format: png
      layers: p5
      style: default
      transparent: false
      url: "http://sgx.geodatenzentrum.de/wms_topplus_open"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  topplus_web_source:
    req:
      format: png
      layers: web
      style: default
      transparent: false
      url: "http://sgx.geodatenzentrum.de/wms_topplus_open"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  webatlas_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_webatlasberlin"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  zoom_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/berlinzoom"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  baumbestand_0_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_wfs_baumbestand"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  baumbestand_1_source:
    req:
      format: png
      layers: 1
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_wfs_baumbestand"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  baumbestand_3_source:
    req:
      format: png
      layers: 3
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_wfs_baumbestand"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  baumbestand_4_source:
    req:
      format: png
      layers: 4
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_wfs_baumbestand"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  baumbestand_0_1_3_4_merged_source:
    req:
      format: png
      layers: 0,1,3,4
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_wfs_baumbestand"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }

  k_oeffbeleucht_source:
    req:
      format: png
      layers: 0
      style: default
      transparent: false
      url: "https://fbinter.stadt-berlin.de/fb/wms/senstadt/k_oeffbeleucht"
    supported_srs: ["EPSG:25833"]
    type: wms
    wms_opts: { version: 1.3.0 }
