# MapProxy Configuration
# Uses modular approach with separate sources files
# config_layers.yml MUST be first - MapProxy only processes the first file with 'layers' section
base:
  - config_layers.yml
  - sources/fbinter-alkis.yaml
  - sources/fbinter-oeffbeleucht.yaml
  - sources/fbinter-senstadt.yaml
  - sources/gdi-baumbestand.yaml
  - sources/gdi-bdom.yaml
  - sources/gdi-fussgaengernetz.yaml
  - sources/gdi-strassenbefahrung.yaml
  - sources/gdi-tempolimits.yaml
  - sources/gdi-postleitzahlen.yaml
  - sources/gdi-abstell-mikromob.yaml
  - sources/gdi-fahrradreparatur.yaml

# Global configuration
globals: {}

# Grid definitions
grids:
  mercator:
    base: GLOBAL_MERCATOR
    num_levels: 22

# Service configuration
services:
  demo: {}
  tms:
    origin: nw
    use_grid_names: true
