# MapProxy Configuration
# Uses modular approach with separate endpoint files

# Base configurations to include
base:
  - endpoints/fbinter-senstadt.yaml
  - endpoints/fbinter-alkis.yaml
  - endpoints/fbinter-oeffbeleucht.yaml
  - endpoints/gdi-bdom.yaml
  - endpoints/gdi-strassenbefahrung.yaml
  - endpoints/gdi-baumbestand.yaml
  - endpoints/gdi-tempolimits.yaml
  - endpoints/gdi-fussgaengernetz.yaml
  - endpoints/gdi-postleitzahlen.yaml

# Global configuration
globals: {}

# Grid definitions
grids:
  mercator:
    base: GLOBAL_MERCATOR
    num_levels: 22

# Service configuration
services:
  demo: {}
  tms: 
    origin: nw
    use_grid_names: true
